### ISSUE TITLE
Hitting CastleAxe trigger throws an error

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [FullScreenShenanigans/FullScreenMario#290]
Originally reprod in "Random"::"Castle"

**Comment by JoshuaKGoldberg** [comment]
Could not repo in 1-4...

```javascript
FSM.setMap("1-4");
FSM.scrollPlayer(4200);
FSM.shiftHoriz(FSM.player, 322);
```

**Comment by JoshuaKGoldberg** [comment]
Cannot repo in random map either...

**Comment by Geoffrey-A** [comment]
The game freezes when the player touches the CastleAxe. In the console I’ve got a `character undefined` error occurring [here](https://github.com/FullScreenShenanigans/FullScreenMario/blob/master/Source/FullScreenMario.ts#L966).
Above that line adding that the following code
```typescript
if (character === undefined) {
    console.log("boom");
}
```
and placing a breakpoint on it helped me find out that: i === 5 whereas characters.length === 2.

Would it be because `CollideCastleAxe` kills all characters in another thread, thus causing the reduction of size of the `characters` array being iterated?
If this is the case, the only possible solution is synchronization. Array effective modification (nothing prevents from working on a copy) would have to happen only when sensitive functions such as `maintainCharacters` are not being executed.

I have reproduced this bug under firefox (windows, linux), chrome (windows).

**Comment by Geoffrey-A** [comment]
Well simply replacing `console.log` call by `continue` seems to fix it. https://github.com/FullScreenShenanigans/FullScreenMario/pull/307

Let us hope the referenced character is not going to be deleted. I have not checked that.

**Comment by Geoffrey-A** [comment]
I have tested commenting out the `killX` calls in `collideCastleAxe`. The game does not freeze but does behave incorrectly: the player, stuck in the air, moves a few pixels, stops again, and the CastleEnd sound plays again.

**Comment by JoshuaKGoldberg** [comment]
> Would it be because CollideCastleAxe kills all characters in another thread...?

Something like that. I'm guessing having `for (i = characters.length - 1; i >= 0; i -= 1) {` in the `maintainCharacters` loop (instead of increasing from 0 to length) is the culprit - it assumes constant length in `characters`, which is wrong.

> The game does not freeze but does behave incorrectly

Maybe the trigger is happening a second time?

**Comment by JoshuaKGoldberg** [comment]
Ok, PR #308 open. Can you confirm it's a fix?

**Comment by Geoffrey-A** [comment]
Yes I have tested it and it worked.

However, I think it has one weakness my suggested modification does not. 
Changing the array iteration direction may help in that once the index is out of bounds the loop will break next time the stop condition is verified. However if the array size decreases between this index checking `i < characters.length` and the array access `character = characters[i];` (so here just right between 2 instructions), `character` will be undefined.

Indeed, in addition to `maintainCharacters` there is `maintainSolids`, but also `maintainScenary`.

What do you think?

**Comment by JoshuaKGoldberg** [comment]
> right between 2 instructions

Not a problem; JavaScript (in browsers) isn't threaded so that (shouldn't) ever be a problem.

> `maintainScenery` 

True. `maintainScenery` does call `arrayDeleteThing`, which calls the Thing's `onDelete` if it exists; if a scenery ever has an `onDelete` that deletes other sceneries that could be a problem... I'll update the PR.

**Comment by JoshuaKGoldberg** [comment]
PR is in master, I'll close the issue. Let me know if it regresses again :)

**Comment by Geoffrey-A** [comment]
Ok, if it’s not threaded it should indeed be fine.
